// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.RobotMap;
import frc.robot.enums.BlinkinPattern;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class LED extends SubsystemBase {

    private Spark blinkin;

    public LED() {
        blinkin = new Spark(RobotMap.BLINKIN_SPARK);
        addChild("blinkin value", blinkin);
    }

    @Override
    public void periodic() {
    }

    public void setPattern(BlinkinPattern pattern) {
        blinkin.set(pattern.getSparkValue());
    }

    public void stop() {
        blinkin.setVoltage(0);
    }

}
