// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;
import frc.robot.RobotMap;
import frc.robot.commands.EnableLEDs;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class LED extends Subsystem {

    private Spark blinkin;

    public enum BLINKIN_PATTERN {
        CONFETTI(-.87), FIRE_LARGE(-.57), LARSON_SCANNER(-0.01);

        private double sparkValue;

        BLINKIN_PATTERN(double sparkValue) {
            this.sparkValue = sparkValue;
        }

        public double getSparkValue() {
            return sparkValue;
        }
    }

    public LED() {
        blinkin = new Spark(RobotMap.BLINKIN_SPARK);
        addChild("blinkin value", blinkin);
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new EnableLEDs());
    }

    @Override
    public void periodic() {
    }

    public void setPattern(BLINKIN_PATTERN pattern) {
        blinkin.set(pattern.sparkValue);
    }

    public void stop() {
        blinkin.setVoltage(0);
    }

}
